kind: pipeline
type: docker
name: default

steps:
- name: backend
  image: hello-world
  commands:
  when:
    branch:
    - master
    event:
    - push
    - pull_request
- name: slack
  image: plugins/slack
  settings:
    webhook: https://hooks.slack.com/services/...
    channel: dev
    icon_url: https://unsplash.it/256/256/?random
  when:
    status:
    - failure

